#!/bin/bash
export NZLRROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export NZLRDB=nzdb
export NZLRUSER=nzu
export NZLRPASS=12345

echo 'create str_to_table stored procedure...'
nzsql $NZLRDB -f str_to_table.sql

echo 'create args_to_table stored procedure...'
nzsql $NZLRDB -f args_to_table.sql

echo 'create create_csv_table stored procedure...'
nzsql $NZLRDB -f create_csv_table.sql

echo 'compile XTXMatrixUdtf udtf...'
nzudxcompile --sig "XTXMatrix(varargs)" --return "TABLE(x int, y int, value double)" --class XTXMatrixUdtf --version 2 XTXMatrixUdtf.cpp --user $NZLRUSER --pw $NZLRPASS --db $NZLRDB --lastcall "TABLE FINAL"

echo 'compile SqMatrixPadUdf udf...'
nzudxcompile --sig "SqMatrixPad(int, int, int, double)" --return "BOOL" --class SqMatrixPadUdf --version 2 SqMatrixPadUdf.cpp --user $NZLRUSER --pw $NZLRPASS --db $NZLRDB --unfenced --nondet

echo 'compile InvSqMatrixPadUdf udf...'
nzudxcompile --sig "InvSqMatrixPad()" --return "BOOL" --class InvSqMatrixPadUdf --version 2 InvSqMatrixPadUdf.cpp --user $NZLRUSER --pw $NZLRPASS --db $NZLRDB --unfenced --nondet --args "-I${NZLRROOT}/include/eigen" 

echo 'compile CalcLRBVecUdtf udtf...'
nzudxcompile --sig "CalcLRBVec(varargs)" --return "TABLE(b int, value double)" --class CalcLRBVecUdtf --version 2 CalcLRBVecUdtf.cpp --user $NZLRUSER --pw $NZLRPASS --db $NZLRDB --unfenced --lastcall "TABLE FINAL"

echo 'create linear_regression stored procedure...'
nzsql $NZLRDB -f linear_regression.sql
